"""Email service for sending notifications."""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any, Optional


class EmailService:
    """Service for sending email notifications."""
    
    def __init__(self, smtp_server: str, smtp_port: int, sender_email: str):
        """
        Initialize email service.
        
        Args:
            smtp_server: SMTP server hostname
            smtp_port: SMTP server port
            sender_email: Sender email address
        """
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.sender_email = sender_email
    
    def send_email(
        self,
        recipient_email: str,
        subject: str,
        data: Dict[str, Any],
        analysis: Optional[str] = None
    ) -> bool:
        """
        Send email with log data and optional analysis.
        
        Args:
            recipient_email: Recipient email address
            subject: Email subject
            data: Log data dictionary
            analysis: Optional LLM analysis text
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            msg = MIMEMultipart('alternative')
            msg['From'] = self.sender_email
            msg['To'] = recipient_email
            msg['Subject'] = subject
            
            # Create email body
            if analysis:
                html_body = self._format_email_with_analysis(data, analysis)
                msg.attach(MIMEText(html_body, 'html'))
            else:
                plain_body = self._format_plain_email(data)
                msg.attach(MIMEText(plain_body, 'plain'))
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.sendmail(self.sender_email, recipient_email, msg.as_string())
            
            print(f"Email sent successfully to {recipient_email}")
            return True
            
        except Exception as e:
            print(f"Failed to send email: {e}")
            return False
    
    def _format_plain_email(self, data: Dict[str, Any]) -> str:
        """Format plain text email body."""
        body = "Database Log Entry:\n\n"
        for key, value in data.items():
            body += f"{key}: {value}\n"
        return body
    
    def _format_email_with_analysis(self, log_data: Dict[str, Any], llm_analysis: str) -> str:
        """Format HTML email body with log data and LLM analysis."""
        # Pre-process the analysis to avoid backslash in f-string
        formatted_analysis = llm_analysis.replace('\n', '<br>')
        
        # Pre-process table rows
        table_rows = []
        for key, value in log_data.items():
            table_rows.append(
                f'<tr><td style="padding: 8px; border-bottom: 1px solid #bdc3c7;"><strong>{key}:</strong></td>'
                f'<td style="padding: 8px; border-bottom: 1px solid #bdc3c7;">{value}</td></tr>'
            )
        table_body = ''.join(table_rows)
        
        html_body = f"""
            <html>
                <body style="font-family: Arial, sans-serif;">
                    <h2 style="color: #2c3e50;">Database Log Entry Analysis</h2>
                    
                    <div style="background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0;">
                        <h3 style="color: #34495e;">Log Details:</h3>
                        <table style="width: 100%; border-collapse: collapse;">
                            {table_body}
                        </table>
                    </div>
                    
                    <div style="background-color: #e8f8f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
                        <h3 style="color: #16a085;">AI-Generated Analysis & Solution:</h3>
                        <div style="white-space: pre-wrap; line-height: 1.6;">
                            {formatted_analysis}
                        </div>
                    </div>
                    
                    <hr style="margin: 30px 0; border: none; border-top: 1px solid #bdc3c7;">
                    <p style="color: #7f8c8d; font-size: 12px;">
                        This is an automated analysis generated by the Database Monitor & Email Service.
                    </p>
                </body>
            </html>
        """
        return html_body
